Version Issue
carterbox/turbo-couscous pull request #1
Opened 2020-07-20 19:48 UTC by bwstarr19

I kept them separate so that the comments would remain.

2020-07-30 19:41 UTC, pep8speaks commented
Hello @bwstarr19! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`benchmarking/reconstruct.py`](https://github.com/tomopy/turbo-couscous/blob/1261bab0cbb5fce499dca96d195b8b553ea7da1f/benchmarking/reconstruct.py):

> [Line 83:80](https://github.com/tomopy/turbo-couscous/blob/1261bab0cbb5fce499dca96d195b8b553ea7da1f/benchmarking/reconstruct.py#L83): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (125 > 79 characters)
> [Line 90:3](https://github.com/tomopy/turbo-couscous/blob/1261bab0cbb5fce499dca96d195b8b553ea7da1f/benchmarking/reconstruct.py#L90): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four

2020-07-30 20:26 UTC, bwstarr19 commented
This is an update which includes the previously unused algorithms in the reconstruction file.

2020-08-06 16:59 UTC, carterbox requested changes
Please restore tests of the accelerated sirt and mlem functions.

2020-08-13 15:22 UTC, carterbox commented on benchmarking/project.py
> +                    prob=float(salt_pepper[1]), val=float(salt_pepper[2]))
Cannot cast from None to float.

2020-08-13 15:24 UTC, carterbox commented on benchmarking/project.py
> +    'as well as the mean and standard deviation as well.',
Make these help strings more specific.

2020-08-17 15:15 UTC, carterbox approved these changes
Just fix these style issues, and then it looks ready to merge. Thanks, @bwstarr19!

2020-08-17 15:15 UTC, carterbox commented on benchmarking/project.py
>      '--salt_pepper',
```suggestion
    '-s',
    '--salt-pepper',
```
Generally, flags are exactly one letter or whole words separated by `-`.

2020-08-17 15:15 UTC, carterbox commented on benchmarking/project.py
> +    if guassian[0]>0 or guassian[1]>0:
```suggestion
    if guassian[0] > 0 or guassian[1] > 0:
```

2020-08-20 15:05 UTC, merged